[project]
name = "notebook-feedback-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.10.0",
    "nbformat>=5.10.4",
    "pyyaml>=6.0.2",
    "streamlit>=1.44.0",
    "tomli-w>=1.2.0",
]
